name: Run checks

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: ['master']

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci

      - name: SvelteKit Check
        run: npm run check

      - name: Prettier and Eslint
        run: npm run lint

      - name: Tests
        run: npm run test
